#!/usr/bin/env python3
"""Añade lotes de vocabulario a `content/vocab/<nivel>.tsv`.

Idempotente: salta las palabras cuya forma base ya existe en cualquier nivel, y
continúa la numeración de ids desde el último emitido, **sin reasignar ninguno**
— el progreso SRS del aprendiz vive en `localStorage['srs:<id>']`.

Uso: python3 tools/vocab_lote.py
Después: python3 tools/build_vocab.py
"""

import csv
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CANON = ROOT / "content" / "vocab"
FIELDS = ("id", "front", "definition", "example", "translation", "tags")
LEVELS = ("a1", "a2", "b1", "b2")

# (front, definition, example, translation, tags-extra)
# El tag de nivel se añade solo. «awl» = Academic Word List (Coxhead, 2000).
B2 = [
    ("abstract (adj)", "based on ideas, not physical things", "The paper is too abstract to be useful.", "abstracto", "adjective awl"),
    ("accommodate (v)", "to provide space for; to adapt to", "The hall accommodates 300 people.", "alojar/adaptarse", "verb awl"),
    ("accumulate (v)", "to increase in quantity over time", "Dust accumulates quickly here.", "acumular", "verb awl"),
    ("acknowledge (v)", "to accept that something is true", "She acknowledged the mistake.", "reconocer", "verb awl"),
    ("adequate (adj)", "enough for a purpose, but not more", "The funding is adequate but not generous.", "suficiente/adecuado", "adjective awl"),
    ("advocate (v/n)", "to publicly support; a supporter", "He advocates smaller classes.", "abogar por/defensor", "verb awl"),
    ("allocate (v)", "to give out for a specific purpose", "We allocated two hours to the task.", "asignar", "verb awl"),
    ("alter (v)", "to change slightly", "The plan was altered at the last minute.", "modificar", "verb awl"),
    ("anticipate (v)", "to expect and prepare for", "We didn't anticipate such demand.", "prever/anticipar", "verb awl"),
    ("arbitrary (adj)", "decided by chance or whim, not reason", "The deadline felt arbitrary.", "arbitrario", "adjective awl"),
    ("articulate (v)", "to express an idea clearly", "She articulated her concerns well.", "expresar con claridad", "verb awl"),
    ("aspect (n)", "one part or feature of something", "Cost is only one aspect of the problem.", "aspecto", "noun awl"),
    ("assert (v)", "to state firmly", "He asserted that the data were sound.", "afirmar/sostener", "verb awl"),
    ("attain (v)", "to reach or achieve", "Few attain that level of fluency.", "alcanzar/lograr", "verb awl"),
    ("attribute (v/n)", "to say something is caused by; a quality", "She attributes her success to practice.", "atribuir/atributo", "verb awl"),
    ("autonomy (n)", "the freedom to decide for yourself", "Learners need some autonomy.", "autonomía", "noun awl"),
    ("bias (n)", "an unfair preference or tendency", "The sample had an obvious bias.", "sesgo", "noun awl"),
    ("capacity (n)", "the ability or amount that fits", "Our capacity to learn changes with age.", "capacidad", "noun awl"),
    ("cease (v)", "to stop", "The noise ceased at midnight.", "cesar", "verb awl formal"),
    ("cite (v)", "to mention as an example or source", "She cited three studies.", "citar", "verb awl"),
    ("clarify (v)", "to make clearer", "Could you clarify that point?", "aclarar", "verb awl"),
    ("coincide (v)", "to happen at the same time", "The dates coincide with the holidays.", "coincidir", "verb awl"),
    ("comprehensive (adj)", "including everything relevant", "a comprehensive review of the field", "exhaustivo/integral", "adjective awl"),
    ("comprise (v)", "to consist of", "The course comprises six modules.", "comprender/constar de", "verb awl formal"),
    ("conceive (v)", "to form an idea of", "It's hard to conceive of such a scale.", "concebir", "verb awl"),
    ("conform (v)", "to behave according to rules or norms", "The design conforms to the standard.", "ajustarse/cumplir", "verb awl"),
    ("consecutive (adj)", "following one after another", "three consecutive days of rain", "consecutivo", "adjective awl"),
    ("consolidate (v)", "to make stronger or combine into one", "Sleep consolidates what you learned.", "consolidar", "verb awl"),
    ("constrain (v)", "to limit or restrict", "Time constrains what we can cover.", "limitar/constreñir", "verb awl"),
    ("contradict (v)", "to say the opposite of", "The results contradict the hypothesis.", "contradecir", "verb awl"),
    ("convey (v)", "to communicate an idea or feeling", "The tone conveys impatience.", "transmitir", "verb awl"),
    ("correlate (v)", "to have a mutual relationship", "Exposure correlates with fluency.", "correlacionar", "verb awl"),
    ("credible (adj)", "believable, deserving trust", "a credible explanation", "creíble", "adjective awl"),
    ("criterion (n)", "a standard used to judge (pl. criteria)", "Fluency is one criterion among several.", "criterio", "noun awl irregular-plural"),
    ("crucial (adj)", "extremely important", "Feedback is crucial at this stage.", "crucial", "adjective awl"),
    ("decline (v/n)", "to decrease; to refuse politely", "Enrolment declined last year.", "disminuir/rechazar", "verb awl"),
    ("deduce (v)", "to reach a conclusion by reasoning", "We can deduce the meaning from context.", "deducir", "verb awl"),
    ("deem (v)", "to consider something to be", "The evidence was deemed sufficient.", "considerar/estimar", "verb formal"),
    ("deliberate (adj)", "done on purpose", "a deliberate omission", "deliberado", "adjective awl"),
    ("denote (v)", "to mean or indicate", "The symbol denotes a long vowel.", "denotar", "verb awl"),
    ("deploy (v)", "to put into use or position", "They deployed a new strategy.", "desplegar/emplear", "verb awl"),
    ("deteriorate (v)", "to become worse", "His accent deteriorated without practice.", "deteriorarse", "verb awl"),
    ("devise (v)", "to invent a method or plan", "She devised a simpler test.", "idear/diseñar", "verb awl"),
    ("discern (v)", "to notice or understand with effort", "It's hard to discern a pattern.", "discernir/percibir", "verb awl formal"),
    ("discrete (adj)", "separate and distinct", "two discrete categories", "discreto/separado", "adjective awl"),
    ("disparity (n)", "a clear difference, usually unfair", "the disparity between regions", "disparidad", "noun awl"),
    ("disseminate (v)", "to spread widely", "The findings were disseminated online.", "difundir", "verb awl formal"),
    ("distort (v)", "to change so it is no longer accurate", "The summary distorts the argument.", "distorsionar", "verb awl"),
    ("elaborate (v)", "to give more detail", "Could you elaborate on that?", "detallar/ampliar", "verb awl"),
    ("elicit (v)", "to get a response from someone", "The question elicited no answer.", "provocar/obtener", "verb awl"),
    ("embody (v)", "to represent an idea in a clear form", "The design embodies the principle.", "encarnar", "verb awl"),
    ("emerge (v)", "to come out or become known", "A pattern emerged from the data.", "surgir/emerger", "verb awl"),
    ("empirical (adj)", "based on observation, not theory", "There is little empirical support.", "empírico", "adjective awl"),
    ("encompass (v)", "to include a wide range", "The term encompasses several methods.", "abarcar", "verb awl"),
    ("enhance (v)", "to improve the quality of", "Sleep enhances retention.", "mejorar/realzar", "verb awl"),
    ("entail (v)", "to involve as a necessary part", "Fluency entails a lot of listening.", "conllevar/implicar", "verb awl"),
    ("erode (v)", "to wear away gradually", "Confidence erodes without practice.", "erosionar", "verb awl"),
    ("exacerbate (v)", "to make a bad situation worse", "Rushing exacerbates the problem.", "agravar", "verb awl formal"),
    ("exemplify (v)", "to be a typical example of", "This case exemplifies the trend.", "ejemplificar", "verb awl"),
    ("exert (v)", "to apply force or influence", "Peers exert a strong influence.", "ejercer", "verb awl"),
    ("explicit (adj)", "stated clearly and directly", "explicit grammar instruction", "explícito", "adjective awl"),
    ("exploit (v)", "to use fully; to use unfairly", "The method exploits spaced repetition.", "aprovechar/explotar", "verb awl"),
    ("feasible (adj)", "possible to do in practice", "Thirty minutes a day is feasible.", "factible/viable", "adjective awl"),
    ("fluctuate (v)", "to rise and fall irregularly", "Motivation fluctuates over months.", "fluctuar", "verb awl"),
    ("formulate (v)", "to express or devise carefully", "He formulated a clear hypothesis.", "formular", "verb awl"),
    ("foster (v)", "to encourage the development of", "The class fosters risk-taking.", "fomentar", "verb awl"),
    ("fundamental (adj)", "forming a necessary base", "a fundamental difference", "fundamental", "adjective awl"),
    ("hamper (v)", "to make progress difficult", "Anxiety hampers production.", "dificultar/obstaculizar", "verb"),
    ("hierarchy (n)", "a system ranked by level", "a hierarchy of difficulty", "jerarquía", "noun awl"),
    ("hinder (v)", "to slow or prevent progress", "Translating word by word hinders fluency.", "impedir/estorbar", "verb awl"),
    ("hypothesis (n)", "an idea to be tested (pl. hypotheses)", "The hypothesis was not supported.", "hipótesis", "noun awl irregular-plural"),
    ("impede (v)", "to obstruct or delay", "Noise impedes comprehension.", "impedir", "verb awl formal"),
    ("implement (v)", "to put a plan into action", "We implemented the change in March.", "implementar/aplicar", "verb awl"),
    ("implicit (adj)", "suggested but not stated", "implicit learning through exposure", "implícito", "adjective awl"),
    ("incur (v)", "to become subject to a cost or loss", "You may incur additional fees.", "incurrir en", "verb awl formal"),
    ("indispensable (adj)", "absolutely necessary", "Practice is indispensable.", "indispensable", "adjective"),
    ("induce (v)", "to cause or persuade", "The drug induces drowsiness.", "inducir/provocar", "verb awl"),
    ("inevitable (adj)", "certain to happen", "Some errors are inevitable.", "inevitable", "adjective awl"),
    ("infer (v)", "to conclude from evidence", "We can infer the meaning from context.", "inferir", "verb awl"),
    ("inherent (adj)", "existing as a natural part", "an inherent limitation of the method", "inherente", "adjective awl"),
    ("initiate (v)", "to start something", "She initiated the conversation.", "iniciar", "verb awl"),
    ("integral (adj)", "necessary to make something complete", "Feedback is integral to learning.", "integral/esencial", "adjective awl"),
    ("integrate (v)", "to combine into a whole", "The course integrates all four skills.", "integrar", "verb awl"),
    ("intervene (v)", "to become involved to change something", "The teacher intervened early.", "intervenir", "verb awl"),
    ("intrinsic (adj)", "belonging naturally; from within", "intrinsic motivation", "intrínseco", "adjective awl"),
    ("isolate (v)", "to separate from others", "We isolated one variable.", "aislar", "verb awl"),
    ("latter (adj)", "the second of two mentioned", "Of the two, the latter is cheaper.", "el último (de dos)", "adjective awl"),
    ("magnitude (n)", "great size or importance", "the magnitude of the effect", "magnitud", "noun awl"),
    ("manifest (v/adj)", "to show clearly; obvious", "Anxiety manifests as silence.", "manifestar(se)", "verb awl"),
    ("mediate (v)", "to help two sides reach agreement", "Social interaction mediates learning.", "mediar", "verb awl"),
    ("mere (adj)", "nothing more than", "a mere coincidence", "simple/mero", "adjective"),
    ("methodology (n)", "the set of methods used", "The methodology was clearly described.", "metodología", "noun awl"),
    ("negligible (adj)", "so small it can be ignored", "The difference was negligible.", "insignificante", "adjective awl"),
    ("notion (n)", "an idea or belief", "the notion of a critical period", "noción/idea", "noun awl"),
    ("obscure (adj/v)", "not well known; to hide", "The point is obscured by jargon.", "oscuro/ocultar", "adjective awl"),
    ("offset (v)", "to balance one thing against another", "Gains offset the initial cost.", "compensar", "verb awl"),
    ("omit (v)", "to leave out", "He omitted the third person -s.", "omitir", "verb awl"),
    ("onset (n)", "the beginning of something", "the onset of adolescence", "inicio/comienzo", "noun"),
    ("outweigh (v)", "to be greater in value than", "The benefits outweigh the effort.", "pesar más que", "verb"),
    ("overt (adj)", "done openly, not hidden", "overt correction of errors", "abierto/manifiesto", "adjective awl"),
    ("paramount (adj)", "more important than anything else", "Clarity is paramount here.", "primordial", "adjective formal"),
    ("pertinent (adj)", "relevant to the matter", "a pertinent question", "pertinente", "adjective awl formal"),
    ("phenomenon (n)", "an observable fact (pl. phenomena)", "a well-documented phenomenon", "fenómeno", "noun awl irregular-plural"),
    ("plausible (adj)", "seeming reasonable or probable", "a plausible explanation", "plausible/verosímil", "adjective awl"),
    ("preclude (v)", "to make impossible", "Cost precludes a larger sample.", "impedir/excluir", "verb formal"),
    ("predominant (adj)", "most common or strongest", "the predominant view in the field", "predominante", "adjective awl"),
    ("presume (v)", "to suppose something is true", "I presume you've read it.", "presumir/suponer", "verb awl"),
    ("prompt (v)", "to cause an action or response", "The image prompted a memory.", "provocar/inducir", "verb"),
    ("proponent (n)", "someone who supports an idea", "a proponent of extensive reading", "partidario", "noun"),
    ("rationale (n)", "the reasons behind a decision", "the rationale for spaced repetition", "fundamento/razón", "noun awl"),
    ("refute (v)", "to prove that something is wrong", "The study refutes that claim.", "refutar", "verb formal"),
    ("reinforce (v)", "to make stronger", "Retrieval reinforces memory.", "reforzar", "verb awl"),
    ("resilient (adj)", "able to recover quickly", "Resilient learners keep going.", "resiliente", "adjective"),
    ("retain (v)", "to keep or hold on to", "You retain what you retrieve.", "retener", "verb awl"),
    ("robust (adj)", "strong and reliable", "a robust finding", "robusto/sólido", "adjective"),
    ("salient (adj)", "most noticeable or important", "the salient features of the text", "destacado/saliente", "adjective formal"),
    ("scarce (adj)", "not enough; hard to find", "Water is scarce in the region.", "escaso", "adjective awl"),
    ("simultaneous (adj)", "happening at the same time", "simultaneous translation", "simultáneo", "adjective awl"),
    ("stem from (phr v)", "to be caused by", "The error stems from the L1.", "derivarse de", "phrasal-verb"),
    ("substantial (adj)", "large in amount or importance", "a substantial improvement", "considerable/sustancial", "adjective awl"),
    ("supersede (v)", "to replace something older", "The new model supersedes the old one.", "reemplazar/sustituir", "verb formal"),
    ("tentative (adj)", "not certain; provisional", "a tentative conclusion", "provisional/tentativo", "adjective"),
    ("threshold (n)", "the level at which something starts", "a threshold of comprehension", "umbral", "noun"),
    ("underpin (v)", "to support or form the basis of", "Five principles underpin the method.", "sustentar/apuntalar", "verb"),
    ("viable (adj)", "able to work successfully", "a viable alternative", "viable", "adjective"),
    ("warrant (v)", "to justify or deserve", "The claim warrants closer study.", "justificar/merecer", "verb formal"),
    ("widespread (adj)", "existing in many places", "a widespread misconception", "generalizado", "adjective"),
    ("yield (v/n)", "to produce a result; output", "The method yields better retention.", "producir/rendimiento", "verb awl"),
]

A2 = [
    # ── Chunks funcionales: lo que más rinde a A2 ──────────────────────────
    ("I'd rather (chunk)", "used to say what you prefer", "I'd rather stay home tonight.", "preferiría", "chunk"),
    ("How about…? (chunk)", "used to suggest something", "How about meeting at seven?", "¿qué tal…?", "chunk"),
    ("It depends on (chunk)", "the result changes according to", "It depends on the weather.", "depende de", "chunk"),
    ("on my own (chunk)", "alone, without help", "I did it on my own.", "por mi cuenta/solo", "chunk"),
    ("at least (chunk)", "not less than; anyway", "It costs at least fifty euros.", "al menos", "chunk"),
    ("as soon as (chunk)", "immediately when", "Call me as soon as you arrive.", "en cuanto", "chunk"),
    ("in order to (chunk)", "for the purpose of", "She left early in order to catch the bus.", "para/con el fin de", "chunk"),
    ("by the way (chunk)", "used to add something not related", "By the way, did you call her?", "por cierto", "chunk"),
    ("no wonder (chunk)", "it is not surprising", "No wonder you're tired!", "no me extraña", "chunk"),
    ("make up your mind (chunk)", "to decide", "Hurry up and make up your mind.", "decidirse", "chunk"),
    ("get in touch (chunk)", "to contact someone", "I'll get in touch next week.", "ponerse en contacto", "chunk"),
    ("keep in mind (chunk)", "to remember when deciding", "Keep in mind that it closes at six.", "tener en cuenta", "chunk"),
    ("on time (chunk)", "not late", "The train left on time.", "a tiempo/puntual", "chunk"),
    ("in a hurry (chunk)", "needing to go fast", "Sorry, I'm in a hurry.", "con prisa", "chunk"),
    ("out of order (chunk)", "not working (machine)", "The lift is out of order.", "fuera de servicio", "chunk"),
    ("used to (chunk)", "a past habit that stopped", "I used to play football.", "solía", "chunk"),
    ("be about to (chunk)", "going to happen very soon", "I was about to call you.", "estar a punto de", "chunk"),
    ("had better (chunk)", "strong advice", "You'd better take a coat.", "más vale que", "chunk"),
    ("as well (chunk)", "also", "She speaks French as well.", "también", "chunk"),
    ("a couple of (chunk)", "two or a few", "I need a couple of days.", "un par de", "chunk"),
    # ── Phrasal verbs de uso diario ───────────────────────────────────────
    ("turn down (phr v)", "to lower; to reject an offer", "Could you turn down the music?", "bajar/rechazar", "phrasal-verb"),
    ("put on (phr v)", "to dress in; to switch on", "Put on your shoes.", "ponerse", "phrasal-verb"),
    ("take out (phr v)", "to remove; to withdraw", "He took out his wallet.", "sacar", "phrasal-verb"),
    ("look up (phr v)", "to search for information", "Look it up in the dictionary.", "buscar (en una fuente)", "phrasal-verb"),
    ("get on (phr v)", "to board; to have a relationship", "We got on the bus at nine.", "subir a/llevarse bien", "phrasal-verb"),
    ("run into (phr v)", "to meet by chance", "I ran into Ana at the market.", "encontrarse con", "phrasal-verb"),
    ("come across (phr v)", "to find by chance", "I came across an old photo.", "encontrar por casualidad", "phrasal-verb"),
    ("work out (phr v)", "to exercise; to end well", "It worked out in the end.", "hacer ejercicio/salir bien", "phrasal-verb"),
    ("fill in (phr v)", "to write information in a form", "Please fill in this form.", "rellenar", "phrasal-verb"),
    ("throw away (phr v)", "to put in the rubbish", "Don't throw away the receipt.", "tirar/desechar", "phrasal-verb"),
    ("hang up (phr v)", "to end a phone call", "She hung up before I finished.", "colgar (el teléfono)", "phrasal-verb"),
    ("pick up (phr v)", "to lift; to collect someone", "I'll pick you up at eight.", "recoger", "phrasal-verb"),
    ("set up (phr v)", "to arrange or start", "They set up a small business.", "montar/establecer", "phrasal-verb"),
    ("sort out (phr v)", "to solve or organise", "We need to sort out this problem.", "resolver/arreglar", "phrasal-verb"),
    ("check in (phr v)", "to register at a hotel or airport", "We checked in at noon.", "registrarse/facturar", "phrasal-verb"),
    ("get over (phr v)", "to recover from", "It took a week to get over the flu.", "recuperarse de", "phrasal-verb"),
    ("hold on (phr v)", "to wait", "Hold on a second, please.", "esperar un momento", "phrasal-verb"),
    ("turn up (phr v)", "to arrive, often unexpectedly", "He turned up an hour late.", "aparecer/presentarse", "phrasal-verb"),
    ("give back (phr v)", "to return something", "Give me back my pen.", "devolver", "phrasal-verb"),
    ("take care of (phr v)", "to look after", "Who takes care of the dog?", "cuidar de", "phrasal-verb"),
    # ── Verbos de alta utilidad ───────────────────────────────────────────
    ("accept (v)", "to agree to take or receive", "She accepted the invitation.", "aceptar", "verb"),
    ("admit (v)", "to say that something is true", "He admitted his mistake.", "admitir", "verb"),
    ("advise (v)", "to tell someone what you think they should do", "The doctor advised me to rest.", "aconsejar", "verb"),
    ("appear (v)", "to seem; to become visible", "She appears tired.", "parecer/aparecer", "verb"),
    ("apply (v)", "to make a formal request", "I applied for the job.", "solicitar", "verb"),
    ("arrange (v)", "to organise or plan", "We arranged a meeting.", "organizar/concertar", "verb"),
    ("avoid (v)", "to keep away from", "Try to avoid the rush hour.", "evitar", "verb"),
    ("belong (v)", "to be owned by; to be part of", "This book belongs to me.", "pertenecer", "verb"),
    ("borrow (v)", "to take and use temporarily", "Can I borrow your charger?", "prestado (pedir)", "verb"),
    ("breathe (v)", "to take air in and out", "Breathe slowly and relax.", "respirar", "verb"),
    ("cancel (v)", "to stop a planned event", "They cancelled the flight.", "cancelar", "verb"),
    ("celebrate (v)", "to do something special for an event", "We celebrated her birthday.", "celebrar", "verb"),
    ("charge (v)", "to ask a price; to fill with power", "They charged us ten euros.", "cobrar/cargar", "verb"),
    ("compare (v)", "to look at differences and similarities", "Compare the two options.", "comparar", "verb"),
    ("complete (v)", "to finish", "Please complete the form.", "completar", "verb"),
    ("connect (v)", "to join together", "Connect the cable here.", "conectar", "verb"),
    ("cross (v)", "to go from one side to the other", "Cross the street at the lights.", "cruzar", "verb"),
    ("deliver (v)", "to take goods to someone", "They deliver on Saturdays.", "entregar/repartir", "verb"),
    ("describe (v)", "to say what someone or something is like", "Describe your neighbourhood.", "describir", "verb"),
    ("discover (v)", "to find something new", "We discovered a nice café.", "descubrir", "verb"),
    ("discuss (v)", "to talk about something seriously", "Let's discuss it tomorrow.", "discutir/tratar", "verb"),
    ("earn (v)", "to get money by working", "She earns a good salary.", "ganar (dinero)", "verb"),
    ("encourage (v)", "to give someone confidence to do something", "My teacher encouraged me.", "animar", "verb"),
    ("enjoy (v)", "to get pleasure from", "I enjoy cooking.", "disfrutar", "verb"),
    ("fail (v)", "to not succeed", "He failed the exam.", "fallar/suspender", "verb"),
    ("fix (v)", "to repair; to arrange", "Can you fix the tap?", "arreglar", "verb"),
    ("happen (v)", "to take place", "What happened yesterday?", "ocurrir/pasar", "verb"),
    ("hide (v)", "to put out of sight", "She hid the keys.", "esconder", "verb"),
    ("hurry (v)", "to move quickly", "Hurry up, we're late!", "darse prisa", "verb"),
    ("hurt (v)", "to cause pain", "My back hurts.", "doler/herir", "verb"),
    ("imagine (v)", "to form a picture in your mind", "Imagine living there.", "imaginar", "verb"),
    ("improve (v)", "to get better", "My English is improving.", "mejorar", "verb"),
    ("increase (v)", "to become larger in number", "Prices increased last year.", "aumentar", "verb"),
    ("introduce (v)", "to present someone to another", "Let me introduce my sister.", "presentar", "verb"),
    ("invite (v)", "to ask someone to come", "They invited us to dinner.", "invitar", "verb"),
    ("manage (v)", "to succeed in doing something difficult", "I managed to finish on time.", "lograr/conseguir", "verb"),
    ("mention (v)", "to say something briefly", "He mentioned your name.", "mencionar", "verb"),
    ("mind (v)", "to be annoyed by", "Do you mind if I open the window?", "importar/molestar", "verb"),
    ("miss (v)", "to fail to catch; to feel sad without", "I missed the train.", "perder/echar de menos", "verb"),
    ("notice (v)", "to see or become aware of", "I noticed a mistake.", "darse cuenta/notar", "verb"),
    ("order (v)", "to ask for food or goods", "We ordered two coffees.", "pedir/encargar", "verb"),
    ("pack (v)", "to put things in a bag", "I need to pack my suitcase.", "hacer la maleta", "verb"),
    ("prefer (v)", "to like one thing more", "I prefer tea to coffee.", "preferir", "verb"),
    ("promise (v)", "to say you will certainly do something", "He promised to help.", "prometer", "verb"),
    ("realise (v)", "to become aware of a fact", "I realised I was wrong.", "darse cuenta", "verb"),
    ("reduce (v)", "to make smaller", "Reduce the heat and wait.", "reducir", "verb"),
    ("refuse (v)", "to say no to", "She refused the offer.", "rechazar/negarse", "verb"),
    ("relax (v)", "to rest and become calm", "I relax by walking.", "relajarse", "verb"),
    ("remind (v)", "to make someone remember", "Remind me to call her.", "recordar (a alguien)", "verb"),
    ("rent (v)", "to pay to use something", "We rented a car.", "alquilar", "verb"),
    ("repair (v)", "to fix something broken", "They repaired the roof.", "reparar", "verb"),
    ("replace (v)", "to put something new in place of", "I replaced the battery.", "reemplazar", "verb"),
    ("reply (v)", "to answer", "She replied immediately.", "responder", "verb"),
    ("save (v)", "to keep for later; to rescue", "I'm saving for a trip.", "ahorrar/guardar", "verb"),
    ("share (v)", "to divide or use together", "We shared a pizza.", "compartir", "verb"),
    ("solve (v)", "to find an answer to a problem", "Can you solve this?", "resolver", "verb"),
    ("spell (v)", "to say or write the letters of a word", "How do you spell it?", "escribir/deletrear", "verb"),
    ("succeed (v)", "to achieve what you wanted", "She succeeded in the end.", "tener éxito", "verb"),
    ("suppose (v)", "to think something is probably true", "I suppose you're right.", "suponer", "verb"),
    ("surprise (v)", "to cause a feeling of wonder", "The news surprised us.", "sorprender", "verb"),
    ("waste (v)", "to use badly or lose", "Don't waste water.", "desperdiciar", "verb"),
    ("wear (v)", "to have clothes on your body", "She wore a blue dress.", "llevar puesto", "verb irregular"),
    ("wish (v)", "to want something unlikely", "I wish I could go.", "desear/ojalá", "verb"),
    ("wonder (v)", "to want to know; to ask yourself", "I wonder why he left.", "preguntarse", "verb"),
    ("worry (v)", "to feel anxious", "Don't worry about it.", "preocuparse", "verb"),
    # ── Adjetivos de alta frecuencia ──────────────────────────────────────
    ("afraid (adj)", "feeling fear", "I'm afraid of heights.", "asustado/temeroso", "adjective"),
    ("angry (adj)", "feeling strong annoyance", "She was angry with me.", "enfadado", "adjective"),
    ("careful (adj)", "paying attention to avoid harm", "Be careful with that knife.", "cuidadoso", "adjective"),
    ("clever (adj)", "quick to learn", "That's a clever solution.", "listo/ingenioso", "adjective"),
    ("comfortable (adj)", "pleasant to be in or wear", "These shoes are comfortable.", "cómodo", "adjective"),
    ("common (adj)", "happening often", "It's a common mistake.", "común/frecuente", "adjective"),
    ("dangerous (adj)", "likely to cause harm", "Driving there is dangerous.", "peligroso", "adjective"),
    ("delicious (adj)", "tasting very good", "The soup was delicious.", "delicioso", "adjective"),
    ("empty (adj)", "containing nothing", "The room was empty.", "vacío", "adjective"),
    ("famous (adj)", "known by many people", "a famous writer", "famoso", "adjective"),
    ("favourite (adj)", "liked more than others", "This is my favourite song.", "favorito", "adjective"),
    ("foreign (adj)", "from another country", "a foreign language", "extranjero", "adjective"),
    ("healthy (adj)", "good for your body", "a healthy diet", "saludable", "adjective"),
    ("honest (adj)", "telling the truth", "Be honest with me.", "honesto/sincero", "adjective"),
    ("huge (adj)", "extremely large", "a huge difference", "enorme", "adjective"),
    ("ill (adj)", "not healthy", "She's been ill all week.", "enfermo", "adjective"),
    ("lonely (adj)", "sad because you are alone", "He felt lonely at first.", "solo/solitario", "adjective"),
    ("lucky (adj)", "having good fortune", "You're lucky it's open.", "afortunado", "adjective"),
    ("nervous (adj)", "worried about something", "I get nervous before exams.", "nervioso", "adjective"),
    ("polite (adj)", "showing good manners", "He was very polite.", "educado/cortés", "adjective"),
    ("popular (adj)", "liked by many people", "a popular restaurant", "popular", "adjective"),
    ("possible (adj)", "able to happen", "Is it possible to change it?", "posible", "adjective"),
    ("proud (adj)", "pleased about an achievement", "I'm proud of you.", "orgulloso", "adjective"),
    ("rare (adj)", "not happening often", "a rare opportunity", "raro/poco frecuente", "adjective"),
    ("rude (adj)", "not polite", "It's rude to interrupt.", "grosero/maleducado", "adjective"),
    ("safe (adj)", "not in danger", "The area is safe at night.", "seguro", "adjective"),
    ("serious (adj)", "important or worrying; not joking", "It's a serious problem.", "serio/grave", "adjective"),
    ("shy (adj)", "nervous with other people", "She's shy with strangers.", "tímido", "adjective"),
    ("simple (adj)", "easy to understand", "a simple explanation", "sencillo", "adjective"),
    ("strange (adj)", "unusual or surprising", "That's a strange noise.", "extraño", "adjective"),
    ("terrible (adj)", "very bad", "The weather was terrible.", "terrible/malísimo", "adjective"),
    ("tiny (adj)", "extremely small", "a tiny apartment", "diminuto", "adjective"),
    ("useful (adj)", "helpful for a purpose", "That's a useful tip.", "útil", "adjective"),
    ("wrong (adj)", "not correct", "I gave the wrong answer.", "equivocado/incorrecto", "adjective"),
    ("worried (adj)", "feeling anxious", "She looked worried.", "preocupado", "adjective"),
    # ── Adverbios y conectores ────────────────────────────────────────────
    ("probably (adv)", "very likely", "He's probably at home.", "probablemente", "adverb"),
    ("almost (adv)", "nearly but not completely", "I almost missed it.", "casi", "adverb"),
    ("especially (adv)", "more than usual or others", "I like fruit, especially mangoes.", "especialmente", "adverb"),
    ("instead (adv)", "in place of something else", "Let's walk instead.", "en su lugar", "adverb"),
    ("anyway (adv)", "despite that; in any case", "It rained, but we went anyway.", "de todos modos", "adverb"),
    ("hardly (adv)", "almost not at all", "I hardly know her.", "apenas", "adverb"),
    ("besides (adv)", "in addition", "Besides, it's too expensive.", "además", "adverb"),
    ("actually (adv)", "in fact (NOT «actualmente»)", "Actually, I disagree.", "en realidad", "adverb false-friend"),
    ("nearly (adv)", "almost", "It's nearly ready.", "casi", "adverb"),
    ("unfortunately (adv)", "sadly, it is bad news", "Unfortunately, it's closed.", "desafortunadamente", "adverb"),
]

B1 = [
    ("access (n/v)", "the right or way to reach something", "Students have access to the library.", "acceso/acceder", "noun awl"),
    ("adjust (v)", "to change slightly to fit better", "Adjust the volume, please.", "ajustar", "verb awl"),
    ("affect (v)", "to influence or change", "Noise affects concentration.", "afectar", "verb awl"),
    ("annual (adj)", "happening once a year", "the annual report", "anual", "adjective awl"),
    ("apparent (adj)", "easy to see or understand", "It became apparent that he was right.", "aparente/evidente", "adjective awl"),
    ("appreciate (v)", "to value; to understand fully", "I appreciate your help.", "apreciar/valorar", "verb awl"),
    ("arise (v)", "to happen or appear", "A problem arose during the test.", "surgir", "verb awl irregular"),
    ("aware (adj)", "knowing about something", "Are you aware of the risk?", "consciente", "adjective awl"),
    ("brief (adj)", "short in time or length", "a brief explanation", "breve", "adjective awl"),
    ("capable (adj)", "able to do something", "She's capable of much more.", "capaz", "adjective awl"),
    ("commit (v)", "to promise to do; to do something wrong", "He committed to the plan.", "comprometerse", "verb awl"),
    ("communicate (v)", "to share information", "We communicate by email.", "comunicar", "verb awl"),
    ("concentrate (v)", "to focus your attention", "I can't concentrate with the noise.", "concentrarse", "verb awl"),
    ("confirm (v)", "to say that something is definitely true", "Please confirm your booking.", "confirmar", "verb awl"),
    ("conflict (n)", "a serious disagreement", "a conflict between the two groups", "conflicto", "noun awl"),
    ("constant (adj)", "happening all the time; not changing", "constant interruptions", "constante", "adjective awl"),
    ("contact (v/n)", "to communicate with someone", "Contact us for more information.", "contactar/contacto", "verb awl"),
    ("contemporary (adj)", "of the present time", "contemporary music", "contemporáneo", "adjective awl"),
    ("contribute (v)", "to give a part to something", "Everyone contributed ideas.", "contribuir", "verb awl"),
    ("convert (v)", "to change into another form", "Convert the file to PDF.", "convertir", "verb awl"),
    ("core (n/adj)", "the most important part", "the core of the argument", "núcleo/central", "noun awl"),
    ("correspond (v)", "to match; to exchange letters", "The numbers don't correspond.", "corresponder", "verb awl"),
    ("crisis (n)", "a time of great difficulty (pl. crises)", "an economic crisis", "crisis", "noun awl irregular-plural"),
    ("cycle (n)", "a series of events that repeat", "the sleep cycle", "ciclo", "noun awl"),
    ("decade (n)", "a period of ten years", "over the last decade", "década", "noun awl"),
    ("detect (v)", "to discover or notice", "The test detects small changes.", "detectar", "verb awl"),
    ("dimension (n)", "a measurement or aspect", "another dimension of the problem", "dimensión", "noun awl"),
    ("display (v/n)", "to show", "The screen displays the results.", "mostrar/pantalla", "verb awl"),
    ("diverse (adj)", "very different from each other", "a diverse group of students", "diverso", "adjective awl"),
    ("document (n/v)", "a written record; to record", "Save the document.", "documento/documentar", "noun awl"),
    ("domestic (adj)", "of the home or a country's own", "domestic flights", "doméstico/nacional", "adjective awl"),
    ("dominate (v)", "to be the strongest", "One theory dominated the field.", "dominar", "verb awl"),
    ("draft (n/v)", "a first version", "This is only a first draft.", "borrador", "noun awl"),
    ("dramatic (adj)", "sudden and noticeable", "a dramatic improvement", "drástico/espectacular", "adjective awl"),
    ("dynamic (adj)", "always changing; full of energy", "a dynamic classroom", "dinámico", "adjective awl"),
    ("enforce (v)", "to make people obey a rule", "The rule is rarely enforced.", "hacer cumplir", "verb awl"),
    ("enormous (adj)", "extremely large", "an enormous difference", "enorme", "adjective awl"),
    ("equivalent (adj/n)", "equal in value or meaning", "There is no exact equivalent.", "equivalente", "adjective awl"),
    ("error (n)", "a mistake", "a common error among learners", "error", "noun awl"),
    ("ethical (adj)", "morally right", "an ethical decision", "ético", "adjective awl"),
    ("evolve (v)", "to develop gradually", "The language has evolved.", "evolucionar", "verb awl"),
    ("exceed (v)", "to be greater than a limit", "Costs exceeded the budget.", "exceder/superar", "verb awl"),
    ("exhibit (v)", "to show publicly or display a quality", "He exhibits great patience.", "exhibir/mostrar", "verb awl"),
    ("expert (n/adj)", "someone with special knowledge", "an expert in phonetics", "experto", "noun awl"),
    ("expose (v)", "to make visible or subject to", "Learners must be exposed to real speech.", "exponer", "verb awl"),
    ("extract (v/n)", "to take out; a short passage", "an extract from the novel", "extraer/extracto", "verb awl"),
    ("flexible (adj)", "able to change easily", "flexible working hours", "flexible", "adjective awl"),
    ("framework (n)", "a basic structure of ideas", "a theoretical framework", "marco", "noun awl"),
    ("gender (n)", "the state of being male or female", "gender differences in the data", "género", "noun awl"),
    ("generation (n)", "all the people born around the same time", "the younger generation", "generación", "noun awl"),
    ("guarantee (v/n)", "to promise something will happen", "Practice doesn't guarantee fluency.", "garantizar", "verb awl"),
    ("guideline (n)", "advice on how to do something", "follow the guidelines", "directriz/pauta", "noun awl"),
    ("highlight (v)", "to draw attention to", "The study highlights a gap.", "destacar/resaltar", "verb awl"),
    ("hence (adv)", "for this reason", "It rained; hence the delay.", "por tanto", "adverb awl formal"),
    ("illustrate (v)", "to show with an example", "This case illustrates the point.", "ilustrar", "verb awl"),
    ("impose (v)", "to force something on someone", "They imposed a new rule.", "imponer", "verb awl"),
    ("index (n)", "an alphabetical list; a measure", "Check the index at the back.", "índice", "noun awl"),
    ("initiative (n)", "a new plan; the ability to act alone", "a government initiative", "iniciativa", "noun awl"),
    ("insight (n)", "a clear understanding", "The study offers useful insight.", "perspicacia/visión", "noun awl"),
    ("instance (n)", "an example or case", "in this instance", "caso/instancia", "noun awl"),
    ("intense (adj)", "very strong", "intense concentration", "intenso", "adjective awl"),
    ("interact (v)", "to communicate or act together", "Learners interact in pairs.", "interactuar", "verb awl"),
    ("justify (v)", "to give a good reason for", "How do you justify that claim?", "justificar", "verb awl"),
    ("layer (n)", "a level or thickness", "another layer of meaning", "capa", "noun awl"),
    ("lecture (n)", "a formal talk to teach", "a lecture on phonology", "conferencia/clase magistral", "noun awl"),
    ("link (v/n)", "to connect", "The two ideas are linked.", "vincular/enlace", "verb awl"),
    ("locate (v)", "to find the position of", "Can you locate the error?", "localizar", "verb awl"),
    ("logical (adj)", "sensible and reasonable", "a logical conclusion", "lógico", "adjective awl"),
    ("mechanism (n)", "a process or system that produces a result", "the mechanism behind forgetting", "mecanismo", "noun awl"),
    ("media (n)", "newspapers, TV and internet together", "social media", "medios de comunicación", "noun awl"),
    ("mental (adj)", "of the mind", "mental effort", "mental", "adjective awl"),
    ("minimal (adj)", "very small in amount", "minimal effort", "mínimo", "adjective awl"),
    ("minor (adj)", "small and not important", "a minor error", "menor/leve", "adjective awl"),
    ("modify (v)", "to change slightly", "We modified the design.", "modificar", "verb awl"),
    ("monitor (v)", "to watch and check over time", "Monitor your progress weekly.", "supervisar/controlar", "verb awl"),
    ("negative (adj)", "bad or harmful; saying no", "a negative effect", "negativo", "adjective awl"),
    ("network (n)", "a connected system", "a network of contacts", "red", "noun awl"),
    ("neutral (adj)", "not supporting either side", "a neutral tone", "neutral", "adjective awl"),
    ("nevertheless (adv)", "despite that", "It's hard; nevertheless, it works.", "no obstante", "adverb awl formal"),
    ("objective (n/adj)", "a goal; not influenced by feelings", "Our main objective is fluency.", "objetivo", "noun awl"),
    ("obvious (adj)", "easy to see or understand", "an obvious mistake", "obvio", "adjective awl"),
    ("option (n)", "a choice", "You have three options.", "opción", "noun awl"),
    ("output (n)", "what is produced", "language output", "producción/salida", "noun awl"),
    ("parallel (adj)", "similar and happening at the same time", "a parallel process", "paralelo", "adjective awl"),
    ("passive (adj)", "not active; accepting without acting", "passive listening isn't enough", "pasivo", "adjective awl"),
    ("perspective (n)", "a point of view", "from a different perspective", "perspectiva", "noun awl"),
    ("phase (n)", "a stage in a process", "the first phase of learning", "fase", "noun awl"),
    ("physical (adj)", "of the body or material world", "physical exercise", "físico", "adjective awl"),
    ("precise (adj)", "exact and accurate", "the precise meaning", "preciso", "adjective awl"),
    ("promote (v)", "to encourage; to raise in rank", "This promotes autonomy.", "promover/ascender", "verb awl"),
    ("proportion (n)", "a part compared to the whole", "a large proportion of learners", "proporción", "noun awl"),
    ("pursue (v)", "to continue trying to achieve", "She pursued a career in teaching.", "perseguir/proseguir", "verb awl"),
    ("quote (v/n)", "to repeat someone's exact words", "He quoted the author directly.", "citar/cita", "verb awl"),
    ("random (adj)", "chosen without a pattern", "a random sample", "aleatorio", "adjective awl"),
    ("react (v)", "to respond to something", "How did she react?", "reaccionar", "verb awl"),
    ("recall (v)", "to remember", "I can't recall his name.", "recordar", "verb awl"),
    ("register (n/v)", "the style of language for a situation", "an academic register", "registro", "noun awl"),
    ("reject (v)", "to refuse to accept", "They rejected the proposal.", "rechazar", "verb awl"),
    ("release (v)", "to let go; to make available", "They released the results.", "liberar/publicar", "verb awl"),
    ("restore (v)", "to bring back to a former state", "Sleep restores attention.", "restaurar/restablecer", "verb awl"),
    ("reverse (v/adj)", "to change to the opposite", "The trend has reversed.", "invertir/inverso", "verb awl"),
    ("revise (v)", "to change or study again", "Revise your draft.", "revisar/repasar", "verb awl"),
    ("route (n)", "a way from one place to another", "the fastest route", "ruta", "noun awl"),
    ("schedule (n/v)", "a plan of times", "a tight schedule", "horario/programar", "noun awl"),
    ("shift (n/v)", "a change; a work period", "a shift in attention", "cambio/turno", "noun awl"),
    ("somewhat (adv)", "a little; to some degree", "somewhat surprising", "algo/un poco", "adverb awl"),
    ("specify (v)", "to state exactly", "Specify the deadline.", "especificar", "verb awl"),
    ("stable (adj)", "not likely to change", "a stable result", "estable", "adjective awl"),
    ("statistic (n)", "a number from collected data", "an alarming statistic", "estadística", "noun awl"),
    ("status (n)", "position or state", "the status of the application", "estado/estatus", "noun awl"),
    ("stress (n/v)", "pressure; to emphasise", "He stressed the importance of input.", "estrés/enfatizar", "noun awl"),
    ("submit (v)", "to give in for consideration", "Submit your essay by Friday.", "entregar/presentar", "verb awl"),
    ("summary (n)", "a short version of the main points", "Write a brief summary.", "resumen", "noun awl"),
    ("survive (v)", "to continue to live or exist", "Few languages survive isolation.", "sobrevivir", "verb awl"),
    ("suspend (v)", "to stop temporarily", "The service was suspended.", "suspender", "verb awl"),
    ("symbol (n)", "a sign that represents something", "a phonetic symbol", "símbolo", "noun awl"),
    ("target (n/v)", "something you aim at", "a realistic target", "objetivo/meta", "noun awl"),
    ("task (n)", "a piece of work to do", "a communicative task", "tarea", "noun awl"),
    ("technical (adj)", "relating to a specific skill or science", "technical vocabulary", "técnico", "adjective awl"),
    ("technique (n)", "a particular way of doing something", "a memory technique", "técnica", "noun awl"),
    ("temporary (adj)", "lasting only a short time", "a temporary solution", "temporal/provisional", "adjective awl"),
    ("theme (n)", "the main subject", "the central theme of the text", "tema", "noun awl"),
    ("trend (n)", "a general direction of change", "a growing trend", "tendencia", "noun awl"),
    ("trigger (v)", "to cause something to start", "The word triggered a memory.", "desencadenar", "verb"),
    ("ultimate (adj)", "final or most important", "the ultimate goal", "último/definitivo", "adjective awl"),
    ("undertake (v)", "to start and take responsibility for", "They undertook a large study.", "emprender", "verb awl irregular"),
    ("unique (adj)", "the only one of its kind", "a unique case", "único", "adjective awl"),
    ("valid (adj)", "based on truth or logic; legally usable", "a valid argument", "válido", "adjective awl"),
    ("version (n)", "a form of something that differs", "the latest version", "versión", "noun awl"),
    ("via (prep)", "by way of; using", "We contacted them via email.", "a través de", "preposition awl"),
    ("virtual (adj)", "existing on a computer", "a virtual classroom", "virtual", "adjective awl"),
    ("visible (adj)", "able to be seen", "no visible difference", "visible", "adjective awl"),
    ("visual (adj)", "relating to seeing", "visual memory", "visual", "adjective awl"),
    ("volume (n)", "amount; loudness", "the volume of input", "volumen", "noun awl"),
    ("voluntary (adj)", "done by choice", "voluntary participation", "voluntario", "adjective awl"),
    ("whereas (conj)", "in contrast to the fact that", "He likes reading, whereas she prefers audio.", "mientras que", "conjunction awl formal"),
    # ── Chunks y colocaciones típicas de B1 ───────────────────────────────
    ("as a result (chunk)", "because of that", "As a result, prices fell.", "como resultado", "chunk"),
    ("in addition (chunk)", "also, moreover", "In addition, it saves time.", "además", "chunk"),
    ("on the other hand (chunk)", "used to give a contrasting view", "On the other hand, it's cheaper.", "por otro lado", "chunk"),
    ("in terms of (chunk)", "with regard to", "In terms of cost, it's fine.", "en cuanto a", "chunk"),
    ("take into account (chunk)", "to consider when deciding", "Take the deadline into account.", "tener en cuenta", "chunk"),
    ("play a role (chunk)", "to have an effect or function", "Sleep plays a key role.", "jugar un papel", "chunk"),
    ("to some extent (chunk)", "partly", "That's true to some extent.", "en cierta medida", "chunk"),
    ("bear in mind that (chunk)", "remember that", "Bear in mind that it's optional.", "ten en cuenta que", "chunk"),
    ("give rise to (chunk)", "to cause", "The change gave rise to complaints.", "dar lugar a", "chunk"),
    ("in the long run (chunk)", "over a long period", "It's cheaper in the long run.", "a la larga", "chunk"),
]

LOTES = {"b2": B2, "a2": A2, "b1": B1}


def headword(front: str) -> str:
    return re.sub(r"\s*\(.*?\)", "", front).strip().lower()


def main() -> None:
    # Todas las palabras ya existentes, de todos los niveles: no queremos que la
    # misma palabra aparezca en dos decks.
    existing = {}
    decks = {}
    for lvl in LEVELS:
        path = CANON / f"{lvl}.tsv"
        rows = list(csv.DictReader(path.open(), delimiter="\t"))
        decks[lvl] = rows
        for r in rows:
            existing[headword(r["front"])] = lvl

    for lvl, lote in LOTES.items():
        rows = decks[lvl]
        next_num = max(int(r["id"].split("-")[1]) for r in rows)
        added = skipped = 0

        for front, definition, example, translation, tags in lote:
            key = headword(front)
            if key in existing:
                skipped += 1
                continue
            next_num += 1
            rows.append({
                "id": f"{lvl}-{next_num:03d}",
                "front": front,
                "definition": definition,
                "example": example,
                "translation": translation,
                "tags": f"{lvl} {tags}".strip(),
            })
            existing[key] = lvl
            added += 1

        path = CANON / f"{lvl}.tsv"
        with path.open("w", newline="") as fh:
            w = csv.writer(fh, delimiter="\t", lineterminator="\n")
            w.writerow(FIELDS)
            for r in rows:
                w.writerow([r[c] for c in FIELDS])

        print(f"{lvl}: +{added} nuevas (omitidas {skipped} ya existentes) → {len(rows)} cards")


if __name__ == "__main__":
    main()
